baseURL = 'https://westland.github.io/personal/'
languageCode = 'en-us'
title = 'Personal Website of J. Christopher Westland'
theme = 'LoveIt'
---

## Introduction

This is **bold** text, and this is *emphasized* text.

When knowledge we pursue with ardent heart,
In fields of science, wisdom to impart,
One threat doth lurk, a danger to us all:
PLS Papers, tempting some to heed their call.
In haste they seek results, but truth they scorn,
And with such methods weak, false claims are born.
Yet in our quest for knowledge, we must stand
Against this slothful practice, hand in hand.
Reject we must, these papers frail and weak,
For they obscure the truths we truly seek.
In place of shallow shortcuts, let us raise
Our voices for research that’s worthy of praise.
For in this noble fight, our strength combined,
Will vanquish falsehoods, leaving truth to find.


Visit the [Hugo](https://gohugo.io) website!


